### PR TITLE
Add group and environment excludes

### PR DESCRIPTION
**Pull request by pkratoch**
Tests: https://github.com/rpm-software-management/ci-dnf-stack/pull/1643

### CODE REVIEW

File: include/libdnf5/comps/comps_sack.hpp [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+    CompsSackWeakPtr get_weak_ptr();
+
+    /// @return The `Base` object to which this object belongs.
+    /// @since 5.2
+    libdnf5::BaseWeakPtr get_base() const;
+
+    /// Loads excluded comps from the configuration.
+    /// Uses the `disable_excludes`, `excludegroups` and `excludeenvironments` configuration options for calculation.
+    /// @since 5.2
+    void load_config_excludes();
```
Comment (evan-goode) [inline include/libdnf5/comps/comps_sack.hpp:54]: I suppose we might also have `load_config_includes` or combine these to `load_config_excludes_includes` like package_sack in the future.

**Review by evan-goode — CHANGES_REQUESTED** [review]
Looks good! Could you go ahead and add `excludegroups` and `excludeenvs` to the config documentation, and maybe mention that `disableexcludes` now applies to groups and environments too?

File: include/libdnf5/comps/comps_sack.hpp (hunk 1 above)
Comment (pkratoch) [reply include/libdnf5/comps/comps_sack.hpp:55]: I didn't add includes for groups, because I haven't found a use case for it and I didn't want to add unnecessary config options. But maybe I could rename the method to `load_config_excludes_includes`, so that it's general just in case the options will be added in the future... What do you think?

**Comment by pkratoch** [comment]
> Looks good! Could you go ahead and add `excludegroups` and `excludeenvs` to the config documentation, and maybe mention that `disableexcludes` now applies to groups and environments too?

Good point, I'll add the documentation.

**Comment by pkratoch** [comment]
I added the docs to the last commit, since that's where the options are introduced.

File: include/libdnf5/comps/comps_sack.hpp (hunk 1 above)
Comment (evan-goode) [reply include/libdnf5/comps/comps_sack.hpp:55]: I think it's fine as-is, calling it `load_config_excludes_includes` now might be misleading.

File: include/libdnf5/comps/group/query.hpp [hunk 2]
```diff
@@ -34,9 +35,12 @@ namespace libdnf5::comps {
 
 class LIBDNF_API GroupQuery : public libdnf5::sack::Query<Group> {
 public:
+    using ExcludeFlags = libdnf5::sack::ExcludeFlags;
+
     // Create new query with newly composed groups (using only solvables from currently enabled repositories)
-    explicit GroupQuery(const libdnf5::BaseWeakPtr & base, bool empty = false);
-    explicit GroupQuery(libdnf5::Base & base, bool empty = false);
+    explicit GroupQuery(
+        const libdnf5::BaseWeakPtr & base, ExcludeFlags flags = ExcludeFlags::APPLY_EXCLUDES, bool empty = false);
```
[the remark this answers is not in the document]
Comment (pkratoch) [reply include/libdnf5/comps/group/query.hpp:42]: Sure, I will bring them back. I think we could even use `APPLY_EXCLUDES` as the default, because that shouldn't break anything, given that the excludes options didn't exist up until now, so they are not set to anything, and it will prevent later change of default. But I don't have enough time today, so I'll do it tomorrow.

[the remark this answers is not in the document]
Comment (pkratoch) [reply include/libdnf5/comps/group/query.hpp:42]: Hm... it actually isn't that simple, because then when `GroupQuery(base)` is called, it's not clear which constructor should be used, because both `GroupQuery(libdnf5::Base & base, bool empty = false)` and `GroupQuery(libdnf5::Base & base, ExcludeFlags flags = ExcludeFlags::APPLY_EXCLUDES, bool empty = false)` match. I can see these options:
1. Make the `flags` not optional - then we couldn't easily deprecate and later drop the one without `flags`, but maybe we wouldn't need to and we could keep both anyway; it wouldn't be nice, but it would work.
2. Keep only the one with `flags` - which would mean breaking the API right away.
3. Keep only the one with `flags`, but swap the order of  the `flags` and `empty` arguments - this would technically break the API, but at least the impact would be smaller, because any existing call of the constructor would still work.

[the remark this answers is not in the document]
Comment (evan-goode) [reply include/libdnf5/comps/group/query.hpp:42]: If this change can wait for DNF 5.3 (F42 probably?), then I like (2) the best. It's easy enough for callers to figure out how to update their code since it's a default argument.

**Comment by Conan-Kudo** [comment]
This PR is not complete. It does not look like it implements support for exclusions through "native" CLI options (particularly through `--exclude` or adding `--group-exclude` options). It is also important that the user does not need to figure out the difference between environment, category, and regular groups.

**Comment by pkratoch** [comment]
> This PR is not complete. It does not look like it implements support for exclusions through "native" CLI options (particularly through `--exclude` or adding `--group-exclude` options). It is also important that the user does not need to figure out the difference between environment, category, and regular groups.

The CLI option is not part of this PR (it's tracked in a separate issue https://github.com/rpm-software-management/dnf5/issues/1910 ).

As for differentiating between groups and environments (I am actually not sure if we process categories and if anything uses them anymore), we discussed this within the team and decided to distinguish between them, since there can be an environment and a group with the same name and they are different after all. The question is (but not for this PR) if we want to distinguish between them also for the CLI option or if we can use the `--exclude` option and the `@` notation for all comps (this is probably what I would prefer).

**Comment by Conan-Kudo** [comment]
> The question is (but not for this PR) if we want to distinguish between them also for the CLI option or if we can use the `--exclude` option and the `@` notation for all comps (this is probably what I would prefer).

I'd prefer this too since that's what people are doing now (and not realizing this doesn't work).

File: libdnf5/comps/comps_sack.cpp [hunk 3]
```diff
@@ -0,0 +1,245 @@
...
+const std::set<std::string> CompsSack::Impl::get_config_group_excludes() {
+    return config_group_excludes;
+}
+
+const std::set<std::string> CompsSack::Impl::get_user_environment_excludes() {
+    return user_environment_excludes;
+}
+
+void CompsSack::Impl::add_user_environment_excludes(const std::set<std::string> & excludes) {
+    for (auto exclude : excludes) {
```
Comment (jan-kolarik) [inline libdnf5/comps/comps_sack.cpp:68]: We should avoid the unnecessary copies with `auto &` or `const auto &` if applicable. Also applies for other for loops in this file.

File: include/libdnf5/comps/group/query.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (pkratoch) [reply include/libdnf5/comps/group/query.hpp:42]: Ok, I can do that... but I am not sure about the implications. It will mean we will have:
```
[[deprecated]]
GroupQuery(const libdnf5::BaseWeakPtr & base, bool empty = false)

GroupQuery(const libdnf5::BaseWeakPtr & base, ExcludeFlags flags, bool empty = false)
```
The first one will be deprecated. And we will suggest user to use the one with the mandatory flags argument? This seems a bit strange if the argument will then become optional.

And then later, we will remove the one without the flags and change the one with mandatory flags to having the argument optional? Is that ok as far as API is concerned? Or will we need to deprecate that one as well and introduce new one with the optional flags like this?
```
[[deprecated]]
GroupQuery(const libdnf5::BaseWeakPtr & base, ExcludeFlags flags, bool empty = false)

GroupQuery(const libdnf5::BaseWeakPtr & base, ExcludeFlags flags = ExcludeFlags::APPLY_EXCLUDES, bool empty = false)
```
Also, I would rather see `APPLY_EXCLUDES` as the default from the beginning. It would be consistent with `PackageQuery` and it's better to introduce this default when introducing the feature (when no one is setting the excludes yet) rather than switching it later and risking someone using the API will need to debug why dnf suddenly behaves differently when the config is the same.

[the remark this answers is not in the document]
Comment (jan-kolarik) [reply include/libdnf5/comps/group/query.hpp:42]: Based on our discussion with @pkratoch, if we go with the ^ proposed solution, we do not even need to bump the major version after all. Since there was no group exclude behavior in place before, this technically isn’t a behavior change.

[the remark this answers is not in the document]
Comment (pkratoch) [reply include/libdnf5/comps/group/query.hpp]: I added the constructors according to the proposal (without any deprecation) and removed the version bump. Thank you @jan-kolarik !

**Review by jan-kolarik — APPROVED** [review]
Thanks, nice work there!

**Comment by jan-kolarik** [comment]
There is an unrelated issue with the clang build, which seems to be caused by https://github.com/rpm-software-management/dnf5/pull/2135:

```
/__w/dnf5/dnf5/libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp:198:69: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
  198 |         auto parsed_keys = rpm_signature.parse_key_file(std::string({"file://"}) + key_tfile.get_path().string());
      |
```

I will fix it with a follow-up PR.
