### ISSUE TITLE
libdnf5 plugins written in Python are broken

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#1775]
The usage of Python libdnf5 plugins isn't very clear and is poorly documented, so there's a chance I may have made a mistake. Here’s what I tried to write a plugin in Python:

1. created `/etc/dnf/libdnf5-plugins/python_plugins_loader.conf` config file with this content to enable python_plugins_loader:
```
[main]
name = python_plugins_loader
enabled = 1
```

2. copied `libdnf5-plugins/python_plugins_loader/plugin.py` to a temporary directory
3. set environment variable `LIBDNF_PYTHON_PLUGIN_DIR` to this directory and tried to run dnf5:

```
❯ LIBDNF_PYTHON_PLUGIN_DIR=/home/mblaha/temp/xxx dnf5 repoquery acpi
Cannot load plugin "/etc/dnf/libdnf5-plugins/python_plugins_loader.conf": Cannot load plugin "/home/mblaha/temp/xxx/plugin.py": PyObject_CallObject(plugin_class_constructor, nullptr): TypeError("IPlugin.__init__() missing 1 required positional argument: 'data'")
Cannot load plugins: python_plugins_loader.conf
```
(to get a better error message I also needed to hack `libdnf5::Plugins::load_plugins()` method to not only log the plugin loading failure, but also print it to console. The thing is that the error occurs during base.setup() call, before the log file is created).

I think that the problem is somehow connected with the change introduced by commit 60338b986.
