### ISSUE TITLE
FTBFS with gcc 10.x: 'isatty' was not declared in this scope

### ISSUE THREAD

**Issue by shastah** [rpm-software-management/dnf5#1168]
Trying to build with gcc 10.4.0:
```
[ 48%] Building CXX object libdnf5-cli/CMakeFiles/libdnf5-cli.dir/output/advisorylist.cpp.o
cd /home/rpm/rpmbuild/BUILD/linux-build/libdnf5-cli && /bin/c++ -DGETTEXT_DOMAIN=\"libdnf5-cli\" -DPROJECT_BINARY_DIR=\"/home/rpm/rpmbuild/BUILD/linux-build\" -DPROJECT_SOURCE_DIR=\"/home/rpm/rpmbuild/BUILD\" -DPROJECT_VERSION_MAJOR=5 -DPROJECT_VERSION_MINOR=1 -DPROJECT_VERSION_PATCH=10 -Dlibdnf5_cli_EXPORTS -I/home/rpm/rpmbuild/BUILD/include -I/home/rpm/rpmbuild/BUILD/common -I/home/rpm/rpmbuild/BUILD/libdnf5-cli/. -Wmaybe-uninitialized -fPIC -fmacro-prefix-map=/home/rpm/rpmbuild/BUILD/= -Wall -Wextra -Werror -Wcast-align -Wformat-nonliteral -Wmissing-format-attribute -Wredundant-decls -Wsign-compare -Wtype-limits -Wuninitialized -Wwrite-strings -Werror=unused-result -Wodr -Wconversion -Wl,--as-needed -std=gnu++2a -MD -MT libdnf5-cli/CMakeFiles/libdnf5-cli.dir/output/advisorylist.cpp.o -MF CMakeFiles/libdnf5-cli.dir/output/advisorylist.cpp.o.d -o CMakeFiles/libdnf5-cli.dir/output/advisorylist.cpp.o -c /home/rpm/rpmbuild/BUILD/libdnf5-cli/output/advisorylist.cpp

/home/rpm/rpmbuild/BUILD/libdnf5-cli/output/advisorylist.cpp: In function 'libscols_table* libdnf5::cli::output::create_advisorylist_table(std::string)':
/home/rpm/rpmbuild/BUILD/libdnf5-cli/output/advisorylist.cpp:33:9: error: 'isatty' was not declared in this scope
   33 |     if (isatty(1)) {
      |         ^~~~~~
```
We fix this internally with
```
sed -i '/^#include <libsmartcols/a#include <unistd.h>' libdnf5-cli/output/advisorylist.cpp
```
Interestingly enough, this doesn't seem to be needed with gcc 12.x.

Compiler info:
```
$ gcc --version
gcc (GCC) 10.4.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (GCC) 10.4.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ppisar** [comment]
Thanks for the report. It caused by a missing inclusion of <unistd.h> from libdnf5-cli/output/advisorylist.cpp. I will fix it. Your experience can vary as the header file might or might not be indirectly included by dependent header files.
